### ISSUE TITLE
Notification pops every time I open the menu

### ISSUE THREAD

**Issue by artscoop** [lestcape/Configurable-Menu#83] opened 2015-10-19 22:38 UTC
The desktop notification says 
repos - SourceActor is undefined

using cinnamon latest (2.6.13 20151019)

**Comment by lestcape** [comment] 2015-10-19 22:51
The applet is fully broken as all my other applets and desklets into the new cinnamon version. A lot of important and useful updates of cinnamon (i need to say that), but as a result i need to fix several things. Just for example: https://github.com/linuxmint/Cinnamon/pull/4537

**Comment by bluedxca93** [comment] 2015-10-25 16:51
Hi,
ok saw that.
Opened an issue here on github  for cinnamon showing stark menu earlier: 
https://github.com/linuxmint/Cinnamon/issues/4728
Did somethign change in the way you invoke labels on a custom popmenu label with a custom style?. it doesn work on 2.6.13 for mint but work on 2.6.13 point release from github.
On your applet the change buttton beewteen favorites and programms in win7 style is affected.

**Comment by Viltex** [comment] 2015-11-05 13:28
Same problem on 2.8(beta). Everything is fine but right clicking the menu causes this notification 'repos sourceActor is undefined' and causes cinnamon to crash. The only things that are responsive is CTRL+ALT+BACKSPACE and the menu itself (only mousing over causing it to highlight). I think the notification itself is the cause of everything becoming unresponsive. The logo for the menu doesn't load either.

**Comment by moniNaydenov** [comment] 2015-11-18 16:20
Hi,
Did anyone find a solution to that problem? I'm using Cinnamon 2.8 and the message "repos sourceActor is undefined" pops every time I try to open the menu.

**Comment by cwilli34** [comment] 2015-12-01 20:27
Same here; both what moniNaydenov and Viltex said is happening.

**Comment by cwilli34** [comment] 2015-12-02 15:58
I just sent a pull request that will hopefully fix this particular issue.  I know that lestcape has broken the code up into multiple files, but if you have just one applet.js file in your `configurableMenu@lestcape` directory (you can find at `/home/[username]/.local/share/cinnamon/applets/`), you can replace that applet.js with the file I am attaching.  It fixes it on my version of cinnamon (2.8.5).  Let me know if it doesn't fix yours.  Just change the extension of the file to `.js`

Right now, if I clone what is here in this repository, this applet does not work.  I have installed Configurable-Menu through the Applets settings in cinnamon and edited the applet.js file.

[applet.txt](https://github.com/lestcape/Configurable-Menu/files/49887/applet.txt)

**Comment by moniNaydenov** [comment] 2015-12-11 14:41
Hi,
just tried with cwilli34's fix, and now cinnamon freezes completely when I right-click on the menu.

**Comment by bluedxca93** [comment] 2015-12-11 15:45
yes can confirm not working too.

**Comment by lestcape** [comment] 2015-12-12 06:07
I say is more easy fix the old version this: https://github.com/lestcape/Configurable-Menu/archive/1.7.zip

**Comment by bluedxca93** [comment] 2015-12-12 06:55
hi,

well perhaps its enough to include some few code from 2.6 in applet
while using 2.8 original js files as much as possible.

 maybe a diff from the not so working repos patch would help.

maked a pull request on starkmenu and i suppose its the only way to
write something similar on configurable menu if a win7 style is
wanted. some extended prototypes and functions are different from
2.6.7.

regards bluedxca93

**Comment by lestcape** [comment] 2015-12-12 07:10
@bluedxca93 basically, the difference is the boxpointer and this probably is the cause of the issue. See here the difference:
https://github.com/linuxmint/Cinnamon/issues/4918

**Comment by bluedxca93** [comment] 2015-12-12 08:00
hi,
ok
why can't offset to screen boundary be set in the cinnamon themes as
.em based on screen resolution size.(so that 0 is possible too as well
as 20 pixels or more)?.  Setting this value independant of the theme
is not good , cause on some themes you really see the difference and
patching boxpointer.js for every different theme is not the best
possible solution.

regards
bluedxca93

**Comment by lestcape** [comment] 2015-12-13 02:43
@bluedxca93 The boxpointer is currently patched for all themes in cinnamon and is also patched in configurable menu to prevent the patch as a user decision. What i say is don't use a default distance or not patch the boxpointer, instead if is really something important to cinnamon we can use a custom value to be configure inside the theme. In the theme is where can be decided how the components will be look, so is the place to set this. The problem is that @JosephMcc changed the way as how  the boxpointer is displayed in the border, so right now to implement this feature you need to override his patch, a thing that i don't want to do if he is not agree with that. He is who need to change his own patch. The problem is, if we moved the menu to the corner how is implemented now the pointer will deform, because it has to be in the middle of the actor.

**Comment by JosephMcc** [comment] 2015-12-13 11:18
What is the issue being discussed with the boxpointer here? Is it the amount of space between the menu and monitor edge? I will look at some point to see if that can be set by a themable property. It should be possible but I can't promise anything until I actually try.

**Comment by bluedxca93** [comment] 2015-12-13 12:35
hi,

yes on all general boxpointer applets the space between outer applet
border and screen. this way one theme could look easily as it is
default now and another like mate/xfce with 0 or 1 px value.

kind
regards
bluedxca93

**Comment by lestcape** [comment] 2015-12-13 13:08
@JosephMcc thanks...

**Comment by cwilli34** [comment] 2015-12-15 19:05
Yes @moniNaydenov, it definitely is still an issue.  My fix only took care of the actual notification that kept popping up when trying to use the menu.  I have yet had time to figure out how to fix the right-click issue.

**Comment by lestcape** [comment] 2015-12-16 02:23
This patch was merged 3 days ago: https://github.com/lestcape/Configurable-Menu/commit/9b4040efdc6a2063d47f5a01a36ef5984169a3a3

Can any one reproduced the bug after that?

There are a lot of bugs now, but well... the situation here is the migration to the global menu api. There are a lot of  incompatible things for now.

**Comment by JauchiPoney** [comment] 2016-02-20 20:31
I have the same bug.
Cinnamon 2.8.6, I just upgraded to Linux Mint 17.3 Rosa, and now I have the same bug again.
It shows up whenever I open the menu, and my cinnamon crashes when I right click on the icon.

**Comment by phoe-krk** [comment] 2016-03-22 19:59
Cinnamon 2.8.6 here, debian stretch/sid, whenever I open the menu, this appears.
![zrzut ekranu z 2016-03-22 20-59-00](https://cloud.githubusercontent.com/assets/15045546/13966014/eada51be-f070-11e5-959e-41d55cbf1cf4.png)

**Comment by rekluz** [comment] 2016-03-23 17:43
I was able to restore the panel to the default settings using this command. 
gsettings reset-recursively org.cinnamon

**Comment by phoe-krk** [comment] 2016-03-23 22:57
rekluz: this does reset all the settings, but it doesn't solve the problem. The moment I re-add the configurable menu, the problem reappears.

**Comment by Xmetalfanx** [comment] 2016-11-20 23:46
This is an older thread I see but i am having the same issue with certain menu styles (Vampire, at the moment) on Mint 18 Cinnamon 3.07 ... this may be related to Cinnamon and not a Mint only issue

**Closed** 2016-11-26 07:44 UTC

**Comment by Vrakfall** [comment] 2016-11-26 17:04
Wait, which commit fixed this? [This one](https://github.com/lestcape/Configurable-Menu/commit/ea224597ae613aa86ba473df789d3c9a604e4e50) or [this one](https://github.com/lestcape/Configurable-Menu/commit/eb9333bb985fb5cc772c85227d3fdc074334d50f) or another one?

**Comment by lestcape** [comment] 2016-11-26 17:32
https://github.com/lestcape/Configurable-Menu/commit/ea224597ae613aa86ba473df789d3c9a604e4e50

**Comment by Vrakfall** [comment] 2016-11-26 19:10
@lestcape Thank you ;D
