### ISSUE TITLE
Incompatible with Cinnamon 3.0.6

### ISSUE THREAD

**Issue by ArtyomIsFlash** [lestcape/Configurable-Menu#94] opened 2016-07-15 14:17 UTC
On Cinnamon 3.0.6 (Linux Mint 18 Sarah x64) it spams notifications with an error "repos   sourceActor is undefined" when interacting with it. Also, right-click menu is fully broken. Using the Cinnamon Spices version.

**Comment by feren** [comment] 2016-07-28 16:47
The Cinnamon Spices version, according to a friend is OUTDATED and effectively deprecated, you could try using the one on this repo (copy it to /home/username/.local/share/cinnamon/applets with Show Hidden Files Turned On), or if you're still having problems, I'd suggest replacing the folder of that Configurable Menu with the following PPA's (On Github):
NikoKrause/CinnXPStarkMenu

^ I've tried his fork in Linux Mint 18 and it works the charm and have even bundled it in my own OS because it's that well coded for Cinnamon 3.0.6

**Comment by lestcape** [comment] 2016-09-20 15:50
This is a problem of Configurable Menu, as not work in the new version of cinnamon... Please, close this thread and request it again to the author of the configurable Menu  (he is really lazy)...

**Comment by ArtyomIsFlash** [comment] 2016-09-22 08:57
@lestcape wait, you're an author of Configurable Menu, aren't you?

**Comment by lestcape** [comment] 2016-09-22 12:40
ohhh yes i'm ughh... well i will see what can i do.... but itś difficult

**Comment by feren** [comment] 2016-09-22 17:28
@lestcape You may want to borrow some code from NikoKruase's Configurable Menu (I think he (or someone else) forked it off of yours) to fix your menu...

**Comment by lestcape** [comment] 2016-09-22 20:47
Hi, @feren no thanks. I have two alternative for this...

1- Is create a development brash, move this code to this branch and fix the menu to work again (that's the easy way), but will only work with a lot of problem. Configurable Menu have a lot of lines of code and it's internally a miss as need to be, like he don't follow the cinnamon api...

2- Forget the wrong things and write the menu again as I try to do.

The point 2 not mean also that will be free of bugs, but i try to development a complete different api outside cinnamon scope and not patch things any more. Because that's the problem of Configurable Menu, Something change in cinnamon and as a result i have a broken menu and i have a new patch. This is going to the ridiculous and i need to stop this, just this is not the moment, and was not the moment before. 

Reasons in order of occurrence:
1- The change of the internal api of applets (by scollings).
2 - The implementation of the dynamically panel for cinnamon (by dalkde).
3-  The modification of the boxpointer by Jossem (this is also the cause of "repos sourceActor is undefined").
4- And just now the vertical panel implementation of Browns and next will be that will be removed the box pointer (see the road map).

Don't understand me wrong... I like a lot all of this changes and i considered an amassing Improved, but I speak for Configurable Menu. Hi don't think the same of me...

**Comment by feren** [comment] 2016-09-23 18:23
@lestcape 
Whilst you're at it, you may also want to add Vertical Panel support for later Cinnamon stables... :)

**Comment by lestcape** [comment] 2016-09-23 20:40
Ofcourse...

**Comment by pintubigfoot** [comment] 2016-11-12 08:34
Any update in this? I really miss this menu :)

**Comment by lestcape** [comment] 2016-11-26 07:42
I just make it work on cinnamon 3.2, but i think it's working now for 3.2, 3.0 and 2.8. Could have some troubles in specific options, but it's working.

**Closed** 2016-11-26 07:42 UTC

**Comment by feren** [comment] 2016-11-27 16:23
@lestcape If it supports Vertical Panels in 3.2, then it may not work, that's a thing I've noticed with 3.0, Vertical-Panel-Capable Applets will come up with the same error on 3.0 as each other stopping them from working...

**Comment by lestcape** [comment] 2016-11-27 20:54
The applet don't support vertical panels, and will probably break thing if you try to move it to a vertical panel. There are not reason of why the support of vertical panels will break the applet if this will be done in a good way.
